helpersGOBackend/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('helpersgo/', include(('helpersgo.urls', 'helpersgo'), namespace='helpersgo')),
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

helpersgo/urls.py
# from django.conf.urls import url
# from django.urls import path, include
# from .views import *
# from rest_framework import routers  
# # Cad_un_med_List, Cad_un_med_Create, Cad_un_med_Detail, Cad_un_med_Update, Cad_un_med_Delete

# router = routers.DefaultRouter()
# router.register('servicios', ServicioApiView)
# router.register('subservicios', SubServicioApiView)

# urlpatterns = [
#     url(r'^$', index, name='index'),
#     path('apis/', include(router.urls))
# ]



from django.conf.urls import url
from django.urls import path, include
from .views import *
from rest_framework import routers  
# Cad_un_med_List, Cad_un_med_Create, Cad_un_med_Detail, Cad_un_med_Update, Cad_un_med_Delete

router = routers.DefaultRouter()
router.register('tipodocumento',TipoDocumentoApiView)
router.register('pais',PaisApiView)
router.register('ciudad',CiudadApiView)
router.register('provincia',ProvinciaApiView)
router.register('distrito',DistritoApiView)
router.register('telefono',TelefonoApiView)
router.register('persona',PersonaApiView)
router.register('cliente',ClienteApiView)
router.register('proveedor',ProveedorApiView)
router.register('direccion',DireccionApiView)
router.register('servicios', ServicioApiView)
router.register('subservicios', SubServicioApiView)
router.register('pedido', PedidoApiView)

urlpatterns = [
    url(r'^$', index, name='index'),
    url('prueba/', index2, name='index2'),
    url('listarPorveedor/(?P<pk>\d+)/$', Proveedores_ServicioList.as_view(), name='proveedoresList'),
    path('apis/', include(router.urls))
]

helpersgo/models.py
# from django.db import models

# # Create your models here.
# #YO SOY ALEX CUMPA, intentanto cuarta vez!!

# class TipoDocumento(models.Model):
#     nombre = models.CharField(max_length=50)
#     descripcion = models.CharField(max_length=50)
#     activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
#     activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

# class Pais(models.Model):
#     nombre = models.CharField(max_length=50)
#     descripcion = models.CharField(max_length=50)
#     activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
#     activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

# class Ciudad(models.Model):
#     nombre = models.CharField(max_length=50)
#     descripcion = models.CharField(max_length=50)
#     activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
#     activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

# class Provincia(models.Model):
#     nombre = models.CharField(max_length=50)
#     descripcion = models.CharField(max_length=50)
#     activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
#     activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')
# class Distrito(models.Model):
#     nombre = models.CharField(max_length=50)
#     descripcion = models.CharField(max_length=50)
#     activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
#     activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')


# class Telefono(models.Model):
#     numero = models.CharField(max_length=30)
#     tipo_choices = (('C', 'Cellular'), ('F', 'Fijo'))
#     tipo = models.CharField(max_length=1, choices= tipo_choices, default= 'C')
#     activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
#     activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

# class Persona(models.Model):
#     nombre = models.CharField(max_length=50)
#     apellido_paterno = models.CharField(max_length=50)
#     apellido_materno = models.CharField(max_length=50)
#     tipo_documento = models.ForeignKey(TipoDocumento, null=False, blank=False, on_delete=models.PROTECT)
#     nro_documento = models.CharField(max_length=50)
#     fec_nacimiento = models.DateField()
#     email = models.EmailField()
#     activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
#     activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

# class Cliente(models.Model):
#     usuario = models.CharField(max_length=30, unique= True)
#     password = models.CharField(max_length=100)
#     activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
#     activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

# class Proveedor(models.Model):
#     usuario = models.CharField(max_length=30, unique= True)
#     password = models.CharField(max_length=100)
#     activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
#     activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

# class Direccion(models.Model):
#     persona = models.ForeignKey(Persona, null=False, blank=False, on_delete=models.PROTECT)
#     pais = models.ForeignKey(Pais, null=False, blank=False, on_delete=models.PROTECT)
#     ciudad = models.ForeignKey(Ciudad, null=False, blank=False, on_delete=models.PROTECT)
#     provincia = models.ForeignKey(Provincia, null=False, blank=False, on_delete=models.PROTECT)
#     distrito = models.ForeignKey(Distrito, null=False, blank=False, on_delete=models.PROTECT)
#     direccion = models.CharField(max_length=200)

# class Servicio(models.Model):
#     nombre = models.CharField(max_length=100)
#     descripcion = models.CharField(max_length=50)
#     activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
#     activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

#     def __str__(self):
#         return self.nombre

# class SubServicio(models.Model):
#     servicio = models.ForeignKey(Servicio, null=False, blank=False, on_delete=models.PROTECT)
#     nombre = models.CharField(max_length=100)
#     descripcion = models.CharField(max_length= 50)
#     tarifa_aprox = models.DecimalField(max_digits=12, decimal_places=2)
#     activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
#     activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

#     def __str__(self):
#         return self.nombre


from django.db import models

# Create your models here.

class TipoDocumento(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50)
    activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
    activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

    def __str__(self):
        return self.nombre

class Pais(models.Model):
    codigo = models.CharField(max_length=2, unique = True)
    nombre = models.CharField(max_length=50)
    activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
    activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

    def __str__(self):
        return self.nombre

class Ciudad(models.Model):
    codigo_pais = models.ForeignKey(Pais, to_field='codigo', blank=False, null=False, on_delete=models.PROTECT)
    nombre = models.CharField(max_length=50)
    activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
    activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')
    def __str__(self):
        return self.nombre


class Provincia(models.Model):
    ciudad = models.ForeignKey(Ciudad, blank=False, null=False, on_delete=models.PROTECT)
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50)
    activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
    activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')
    def __str__(self):
        return self.nombre

class Distrito(models.Model):
    provincia = models.ForeignKey(Provincia, blank=False, null=False, on_delete=models.PROTECT)
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=50)
    activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
    activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')
    def __str__(self):
        return self.nombre

class Telefono(models.Model):
    numero = models.CharField(max_length=30)
    tipo_choices = (('C', 'Cellular'), ('F', 'Fijo'))
    tipo = models.CharField(max_length=1, choices= tipo_choices, default= 'C')
    activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
    activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')
    
    def __str__(self):
        return self.numero

class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellido_paterno = models.CharField(max_length=50)
    apellido_materno = models.CharField(max_length=50)
    tipo_documento = models.ForeignKey(TipoDocumento, null=False, blank=False, on_delete=models.PROTECT)
    nro_documento = models.CharField(max_length=50)
    fec_nacimiento = models.DateField()
    email = models.EmailField(unique=True)
    activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
    activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

    def __str__(self):
        return "{} {} {}".format(self.nombre, self.apellido_paterno, self.apellido_materno)

class Cliente(models.Model):
    persona = models.OneToOneField(Persona, null=False, blank=False, on_delete=models.PROTECT)
    usuario = models.CharField(max_length=30, unique= True)
    password = models.CharField(max_length=100)
    activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
    activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

    def __str__(self):
        return self.usuario

class Proveedor(models.Model):
    persona = models.OneToOneField(Persona, null=False, blank=False, on_delete=models.PROTECT)
    usuario = models.CharField(max_length=30, unique= True)
    foto = models.CharField(max_length= 200)
    password = models.CharField(max_length=100)
    activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
    activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')
    
    def __str__(self):
        return self.usuario

class Direccion(models.Model):
    alias = models.CharField(max_length=200)
    persona = models.ForeignKey(Persona, null=False, blank=False, on_delete=models.PROTECT)
    pais = models.ForeignKey(Pais, null=False, blank=False, on_delete=models.PROTECT)
    ciudad = models.ForeignKey(Ciudad, null=False, blank=False, on_delete=models.PROTECT)
    provincia = models.ForeignKey(Provincia, null=False, blank=False, on_delete=models.PROTECT)
    distrito = models.ForeignKey(Distrito, null=False, blank=False, on_delete=models.PROTECT)
    direccion = models.CharField(max_length=200)
    activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
    activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')
    def __str__(self):
        return self.alias
    

class Servicio(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=50)
    icono = models.CharField(max_length=200, null = True, blank = True)
    activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
    activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

    def __str__(self):
        return self.nombre

class SubServicio(models.Model):
    servicio = models.ForeignKey(Servicio, null=False, blank=False, on_delete=models.PROTECT)
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length= 50)
    tarifa_aprox = models.DecimalField(max_digits=12, decimal_places=2)
    activo_choices = (('A', 'Activo'), ('I', 'Inactivo'))
    activo = models.CharField(max_length=1, choices= activo_choices, default= 'A')

    def __str__(self):
        return self.nombre

# Arturo

class Pedido(models.Model):

helpersgo/views.py
# from django.shortcuts import render
# from rest_framework import viewsets
# from .models import *
# from .serializers import *

# # Create your views here.

# def index(request):
#   #  return HttpResponse("Index")
#     return render(request, 'helpersgo/index.html')

# class ServicioApiView(viewsets.ModelViewSet):
#     queryset = Servicio.objects.all()
#     serializer_class = ServicioSerializer

# class SubServicioApiView(viewsets.ModelViewSet):
#     queryset = SubServicio.objects.all()
#     serializer_class = SubServicioSerializer

from django.shortcuts import render
from rest_framework import viewsets
from .models import *
from .serializers import *
from django.views.generic import ListView
# Create your views here.

def index(request):
  #  return HttpResponse("Index")
    return render(request, 'helpersgo/index.html')

def index2(request):
  #  return HttpResponse("Index")
    return render(request, 'helpersgo/index2.html')

class TipoDocumentoApiView(viewsets.ModelViewSet):
    queryset = TipoDocumento.objects.all()
    serializer_class = TipoDocumentoSerializer


class PaisApiView(viewsets.ModelViewSet):
    queryset = Pais.objects.all()
    serializer_class = PaisSerializer

class CiudadApiView(viewsets.ModelViewSet):
    queryset = Ciudad.objects.all()
    serializer_class = CiudadSerializer

class ProvinciaApiView(viewsets.ModelViewSet):
    queryset = Provincia.objects.all()
    serializer_class = ProvinciaSerializer

class DistritoApiView(viewsets.ModelViewSet):
    queryset = Distrito.objects.all()
    serializer_class = DistritoSerializer

class TelefonoApiView(viewsets.ModelViewSet):
    queryset = Telefono.objects.all()
    serializer_class = TelefonoSerializer

class PersonaApiView(viewsets.ModelViewSet):
    queryset = Persona.objects.all()
    serializer_class = PersonaSerializer

class ClienteApiView(viewsets.ModelViewSet):
    queryset = Cliente.objects.all()
    serializer_class = ClienteSerializer

class ProveedorApiView(viewsets.ModelViewSet):
    queryset = Proveedor.objects.all()
    serializer_class = ProveedorSerializer

class DireccionApiView(viewsets.ModelViewSet):
    queryset = Direccion.objects.all()
    serializer_class = DireccionSerializer

class ServicioApiView(viewsets.ModelViewSet):
    queryset = Servicio.objects.all()
    serializer_class = ServicioSerializer

class SubServicioApiView(viewsets.ModelViewSet):
    queryset = SubServicio.objects.all()
    serializer_class = SubServicioSerializer
  
class PedidoApiView(viewsets.ModelViewSet):
    queryset = Pedido.objects.all()
    serializer_class = PedidoSerializer


class Proveedores_ServicioList(ListView):
    model = Proveedor_Servicio
    template_name = 'helpersgo/proveedoresList.html'
    paginate_by = 10
    
    """def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)


        proveedor_value = Proveedores_ServicioList.objects.only('cod_insumo').get(pk=self.kwargs['pk']).cod_insumo
        context['mov_insumos'] = Cad_stock.objects.all().filter(cod_insumo=cadinsumo_value)
        # context['saldo'] = cantidad_mov_ingresos_suma['cantidad_mov__sum'] - cantidad_mov_salida_suma['cantidad_mov__sum']
        # print (context)
        return context
"""
    def get_context_data(self, **kwargs):
        servicioid = self.kwargs.get('pk', 0)
        print("pk")
        print(servicioid)
        context = super(Proveedores_ServicioList, self).get_context_data(**kwargs)
        #Analizar Relacion
        prov_servicios = Proveedor_Servicio.objects.filter(servicio=servicioid).order_by('id').distinct()
        print("provservicios")
        print(prov_servicios)
        provedores = Proveedor.objects.filter(id__in=prov_servicios)
        print("provedores")
        print(context)
        context['provedores'] = provedores
        personasDict = {}
        personasList = []
        for key in provedores:
            print(key.persona)
            personasList.append(key.persona)
#        context['proveedores']
        #print(context['proveedores'])
        context['personas'] = personasList
        return context


    def get_queryset(self):
        query = self.request.GET.get("q")
        if query :
            context = Proveedor.objects.filter(descripcion__icontains=query)
            return context
        else:
            context = Proveedor.objects.all().order_by('id')
            return context

templates/helpersgo/index.html
{% load staticfiles %} {% load static %}
<!DOCTYPE html>
<html lang="en">
  <!--CABECERA-->
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>HELPERSGO</title>
    <link
      href="https://bootswatch.com/4/flatly/bootstrap.min.css"
      rel="stylesheet"
    />
    <link href="{% static 'styles/main2.css' %}" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/43f3cc2ec8.js"></script>
  </head>
  <style>
    img {
      width: 4rem;
    }
  </style>
  <body>

    <!--HEADER-->
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">HELPERSGO</a>
        <img src="{% static 'images/Logo.png' %}" alt="" />
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarColor02"
          aria-controls="navbarColor02"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#"
                >Home <span class="sr-only">(current)</span></a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Registrate</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contactanos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sobre Nosotros</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <!--END HEADER-->

    <!--MAIN-->
    <main>
        {% block content %}
      

      <div class="container">
        <div class="flex direction-column align-content-sb">
          <h3>Encuentra a tu HelpersGO más calificado en tiempo real</h3>
          <div id="divCardServicios" class="flex align-content-sb">
            <div class="card border-success mb-3" data-href="{% url 'helpersgo:proveedoresList' 1 %}" >
              <div class="card-header">Header</div>
              <div class="card-body">
                <h4 class="card-title">Sub Servicios</h4>
                <p class="card-text"></p>
              </div>
            </div>
            <div class="card border-success mb-3" >
              <div class="card-header">Header</div>
              <div class="card-body">
                <h4 class="card-title">Sub Servicios</h4>
              </div>
            </div>
            <div class="card border-success mb-3" >
              <div class="card-header">Header</div>
              <div class="card-body">
                <h4 class="card-title">Sub Servicios</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
      <section>
          <div class="eligenos">
            <h2>
              Contacta profesionales al servicio del hogar desde donde estés
            </h2>
            <div class="eligenos_cards">
              <div class="farase">
                <h5>Fácil</h5>
                <p>
                  Siempre a tu alcance. Obtén acceso a trabajadores
                  calificados desde la palma de tu mano y desde donde estés,
                  de la manera más sencilla.
                </p>
              </div>
              <div class="farase">
                <h5>Rápido</h5>
                <p>
                  Estamos para atenderte cuando más nos necesitas. Programa la
                  visita de un experto al servicio del hogar en cuestión de
                  minutos.
                </p>
              </div>
              <div class="farase">
                <h5>Seguro</h5>
                <p>
                  Nuestros colaboradores pasan por un riguroso proceso de
                  selección, evaluación psicológica y revisión de antecedentes
                  penales.
                </p>
              </div>
            </div>
          </div>
        </section>
        {% endblock %}
    </main>
    <!--END MAIN-->

    <!--FOOTER-->
    <footer>
        <div class="container">
          <div class="redes">
            <ul>
              <li>
                <a href="#"><i class="fab fa-facebook"></i></a>
              </li>
              <li>
                <a href="#"><i class="fab fa-instagram"></i></a>
              </li>
              <li>
                <a href="#"><i class="fa fa-envelope-o"></i></a>
              </li>
              <li>
                <a href="#"><i class="fab fa-youtube"></i></a>
              </li>
            </ul>
          </div>
          <div>
            <h4>Todos los derechos reservados 2019</h4>
          </div>
        </div>
      </footer>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
      integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
      integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
      crossorigin="anonymous"
    ></script>
    {% block scripts %}
    <script>
      let divCardServicios = document.getElementById("divCardServicios");
      let cards = divCardServicios.getElementsByClassName("card");
      var dataServicios;
      var dataSubServicios;

      fetch("https://helpersgo.herokuapp.com/helpersgo/apis/servicios/")
        .then(function(response) {
          console.log(response);
          return response.json();
        })
        .then(function(data) {
          console.log(data);
          dataServicios = data;
        })
        .then(function() {
          fetch("https://helpersgo.herokuapp.com/helpersgo/apis/subservicios/")
            .then(function(response) {
              console.log(response);
              return response.json();
            })
            .then(function(data) {
              console.log(data);
              dataSubServicios = data;
            })
            .then(function() {
              console.log("NEWW");
              console.log(dataServicios);
              console.log(dataSubServicios);
              for (let i = 0; i < dataServicios.length; i++) {
                console.log(dataServicios[i].nombre);
                cards[i].querySelector(".card-header").innerHTML =
                  dataServicios[i].nombre;
                  console.log("card", cards[i])
                  cards[i].addEventListener("click", function(e) {
                    console.log("this card", this)
                    window.location = this.dataset.href
                    }
                  );
                for (let j = 0; j < dataSubServicios.length; j++) {
                  console.log("dataS", dataServicios[i].id);
                  console.log("dataSub", dataSubServicios[j].servicio);
                  if (dataServicios[i].id === dataSubServicios[j].servicio) {
                    console.log("hehehe");
                    let p_element = document.createElement("p");
                    p_element.classList.add("card-text");
                    p_element.innerHTML = dataSubServicios[j].nombre;
                    console.log("p_element", p_element);
                    let carBody = cards[i].querySelector(".card-body");
                    console.log("carbody", carBody);
                    carBody.appendChild(p_element);
                  }
                }
              }
            });
        });
        
      console.log("JOJO");
    </script>
    {% endblock %}
  </body>
</html>

templates/helpersgo/proveedoresList.html
{% extends 'helpersgo/index.html' %} {% block content %}
{% load staticfiles %} {% load static %}
<link href="{% static 'styles/main2.css' %}" rel="stylesheet"/>
<link
  rel="stylesheet"
  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css"
/>
<div class="row">
  <div class="col-lg-12 col-xs-12">
    <div class="container_proveedor">
      {% if personas %} {% for persona in personas %}
      <div class="well">
        <div class="media">
          <a class="pull-left" href="#">
            <img class="media-object" src="http://placekitten.com/150/150" />
          </a>
          <div class="media-body">
            <h4 class="media-heading pull-left">{{persona}}</h4>
            <p class="text-right">{{persona.email}}</p>
            <p>
              Gasfitero capacitado con cuatrocientos cincuenta y tres horas de
              experiencia
            </p>
            <ul class="list-inline list-unstyled">
              <span><i class="glyphicon glyphicon-comment"></i> 2 comments</span>
              <li>|</li>
              <li>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star"></span>
                <span class="glyphicon glyphicon-star-empty"></span>
              </li>
            </ul>
          </div>
        </div>
      </div>
      {% endfor %} {% else %}
      <h2>No Hay Resultados...</h2>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %} {% block scripts %}

{% endblock %}